package edu.tongji.dao;

import edu.tongji.model.Movie;

public interface MovieDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table movie
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    String insert(Movie record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table movie
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int updateByPrimaryKey(Movie record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table movie
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int updateByPrimaryKeySelective(Movie record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table movie
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    Movie selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table movie
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int deleteByPrimaryKey(String id);
}