package edu.tongji.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import edu.tongji.model.ValueOfItems;

public class ValueOfItemsDAOImpl extends SqlMapClientDaoSupport implements ValueOfItemsDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    public ValueOfItemsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    @Override
    public Integer insert(ValueOfItems record) {
        Object newKey = getSqlMapClientTemplate().insert("valueofitems.abatorgenerated_insert",
            record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    @Override
    public int updateByPrimaryKey(ValueOfItems record) {
        int rows = getSqlMapClientTemplate().update(
            "valueofitems.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    @Override
    public int updateByPrimaryKeySelective(ValueOfItems record) {
        int rows = getSqlMapClientTemplate().update(
            "valueofitems.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    @Override
    public ValueOfItems selectByPrimaryKey(Integer id) {
        ValueOfItems key = new ValueOfItems();
        key.setId(id);
        ValueOfItems record = (ValueOfItems) getSqlMapClientTemplate().queryForObject(
            "valueofitems.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /** 
     * @see edu.tongji.dao.ValueOfItemsDAO#selectByFunctionName(java.lang.String)
     */
    @SuppressWarnings("unchecked")
    @Override
    public List<ValueOfItems> selectByFunctionName(String functionName) {
        ValueOfItems key = new ValueOfItems();
        key.setFunctionName(functionName);
        return getSqlMapClientTemplate().queryForList("valueofitems.select_by_functionName", key);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table valueofitems
     *
     * @abatorgenerated Tue Sep 10 14:20:13 CST 2013
     */
    @Override
    public int deleteByPrimaryKey(Integer id) {
        ValueOfItems key = new ValueOfItems();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete(
            "valueofitems.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }
}