package edu.tongji.dao;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import edu.tongji.model.Rating;

public class RatingDAOImpl extends SqlMapClientDaoSupport implements RatingDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rating
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    public RatingDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rating
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    @Override
    public String insert(Rating record) {
        Object newKey = getSqlMapClientTemplate().insert("rating.abatorgenerated_insert", record);
        return (String) newKey;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rating
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    @Override
    public int updateByPrimaryKey(Rating record) {
        int rows = getSqlMapClientTemplate().update("rating.abatorgenerated_updateByPrimaryKey",
            record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table rating
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    @Override
    public int updateByPrimaryKeySelective(Rating record) {
        int rows = getSqlMapClientTemplate().update(
            "rating.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /** 
     * @see edu.tongji.dao.RatingDAO#select(java.util.Map)
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
    @Override
    public List<Rating> select(Map map) {
        List<Rating> ratings = getSqlMapClientTemplate().queryForList(
            "rating.excute_select_default", map);
        return ratings;
    }

    /** 
     * @see edu.tongji.dao.RatingDAO#countTotalItems(int, int)
     */
    @Override
    public int countTotalItems(int itemI, int itemJ) {
        Map<String, String> map = new HashMap<String, String>();
        map.put("first", String.valueOf(itemI));
        map.put("second", String.valueOf(itemJ));
        return (int) getSqlMapClientTemplate().queryForObject("rating.count_total_item", map);
    }

    /** 
     * @see edu.tongji.dao.RatingDAO#countMissingItems(int, int)
     */
    @Override
    public int countMissingItems(int itemI, int itemJ) {
        List<String> list = new ArrayList<String>();
        list.add(String.valueOf(itemI));
        list.add(String.valueOf(itemJ));
        return (int) getSqlMapClientTemplate().queryForObject("rating.count_missing_item", list);
    }

}