package edu.tongji.dao;

import edu.tongji.model.User;

public interface UserDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    String insert(User record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int updateByPrimaryKey(User record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table user
     *
     * @abatorgenerated Tue Sep 10 11:05:22 CST 2013
     */
    int deleteByPrimaryKey(String id);
}