package edu.tongji.model;

import java.util.Date;

public class ValueOfItems {

    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.id
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private Integer id;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.itemI
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private String  itemI;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.itemJ
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private String  itemJ;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.value
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private Double  value;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.functionName
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private String  functionName;
    /**
     * This field was generated by Abator for iBATIS. This field corresponds to the database column valueofitems.GMT_CREATE
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    private Date    GMT_CREATE;

    /**
     * 
     */
    public ValueOfItems() {

    }

    /**
     * @param itemI
     * @param itemJ
     * @param value
     * @param functionName
     * @param gMT_CREATE
     */
    public ValueOfItems(String itemI, String itemJ, Double value, String functionName,
                        Date gMT_CREATE) {
        super();
        this.itemI = itemI;
        this.itemJ = itemJ;
        this.value = value;
        this.functionName = functionName;
        GMT_CREATE = gMT_CREATE;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.id
     * @return  the value of valueofitems.id
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.id
     * @param id  the value for valueofitems.id
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.itemI
     * @return  the value of valueofitems.itemI
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public String getItemI() {
        return itemI;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.itemI
     * @param itemI  the value for valueofitems.itemI
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setItemI(String itemI) {
        this.itemI = itemI;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.itemJ
     * @return  the value of valueofitems.itemJ
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public String getItemJ() {
        return itemJ;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.itemJ
     * @param itemJ  the value for valueofitems.itemJ
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setItemJ(String itemJ) {
        this.itemJ = itemJ;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.value
     * @return  the value of valueofitems.value
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.value
     * @param value  the value for valueofitems.value
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.functionName
     * @return  the value of valueofitems.functionName
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.functionName
     * @param functionName  the value for valueofitems.functionName
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by Abator for iBATIS. This method returns the value of the database column valueofitems.GMT_CREATE
     * @return  the value of valueofitems.GMT_CREATE
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public Date getGMT_CREATE() {
        return GMT_CREATE;
    }

    /**
     * This method was generated by Abator for iBATIS. This method sets the value of the database column valueofitems.GMT_CREATE
     * @param GMT_CREATE  the value for valueofitems.GMT_CREATE
     * @abatorgenerated  Tue Sep 10 14:20:13 CST 2013
     */
    public void setGMT_CREATE(Date GMT_CREATE) {
        this.GMT_CREATE = GMT_CREATE;
    }
}